#include "generate.hpp"
/*
 * ProffieConfig, All-In-One Proffieboard Management Utility
 * Copyright (C) 2023-2026 Ryan Ogurek
 *
 * components/config/priv/generate/generate.cpp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 4 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <algorithm>
#include <cmath>
#include <sstream>

#include <wx/translation.h>

#include "config/blades/bladeconfig.hpp"
#include "config/blades/ws281x.hpp"
#include "config/buttons/button.hpp"
#include "config/config.hpp"
#include "config/misc/injection.hpp"
#include "config/presets/array.hpp"
#include "config/presets/preset.hpp"
#include "config/priv/data.hpp"
#include "config/priv/io.hpp"
#include "config/priv/strings.hpp"
#include "config/settings/define.hpp"
#include "data/choice.hpp"
#include "data/number.hpp"
#include "data/string.hpp"
#include "log/branch.hpp"
#include "log/logger.hpp"
#include "utils/files.hpp"
#include "utils/string.hpp"
#include "utils/version.hpp"
#include "versions/os.hpp"
#include "versions/prop.hpp"

using namespace config;

namespace {

std::optional<std::string> runPreChecks(
    Config&, logging::Branch&
);

void outputTop(std::ostream&, Config&);
void outputTopGeneral(std::ostream&, Config&);
void outputTopProp(std::ostream&, Config&);

void outputProp(std::ostream&, Config&);

void outputPresets(std::ostream&, Config&);
void outputPresetStyles(std::ostream&, Config&);
void outputPresetBlades(std::ostream&, Config&);

void outputButtons(std::ostream&, Config&);

template<typename VAL = std::string>
void outputOpt(std::ostream&, const std::string& opt, const VAL& val);
template<typename VAL = std::string>
void outputOpt(std::ostream&, const std::string& opt);
template<typename VAL = std::string>
void outputDefine(std::ostream&, const std::string& define);
template<typename VAL = std::string>
void outputDefine(std::ostream&, const std::string& define, const VAL& val);

} // namespace

std::optional<std::string> priv::generate(
    const fs::path& filePath, Config& config, logging::Branch *lBranch
) {
    auto& logger{logging::Branch::optCreateLogger("generate()", lBranch)};

    auto precheckErr{runPreChecks(config, *logger.binfo("Running prechecks..."))};
    if (precheckErr) return precheckErr;

    auto outFile{files::openOutput(filePath)};
    if (not outFile.is_open()) {
        return errorMessage(logger, wxTRANSLATE("Could not open config file for output."));
    }

    
    outFile << "/*\n";
    outFile << " * This configuration file was generated by ProffieConfig, created by Ryryog25.\n";
    outFile << " * ProffieConfig is an All-In-One utility for managing your Proffieboard.\n";
    outFile << " * https://proffieconfig.kafrenetrading.com/\n";
    outFile << " *\n";
    outFile << " * Version: " << executableVersion << ", Generator Version: " wxSTRINGIZE(BIN_VERSION) "\n";
    outFile << " */\n\n" << std::flush;

    outputTop(outFile, config);
    outputProp(outFile, config);
    outputPresets(outFile, config);
    outputButtons(outFile, config);

    outFile.close();

    logger.info("Done");
    return std::nullopt;
}

namespace {

std::optional<std::string> runPreChecks(Config& config, logging::Branch& lBranch) {
    using namespace config;
    using namespace config::priv;
    using namespace config::blades;

    auto& logger{lBranch.createLogger("runPreChecks()")};

    auto& settings{config.settings_};
    auto& awareness{config.settings_.bladeAwareness_};

    if (
            data::Bool::Context{awareness.bladeDetect_.enable_}.val() and
            data::String::Context{awareness.bladeDetect_.pin_}.val().empty()
       ) {
        return errorMessage(logger, wxTRANSLATE("Blade Detect Pin cannot be empty."));
    }

    if (data::Bool::Context{awareness.bladeId_.enable_}.val()) {
        if (data::String::Context{awareness.bladeId_.pin_}.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Blade ID Pin cannot be empty."));
        }

        data::Choice::Context idMode{awareness.bladeId_.mode_};
        data::String::Context bridgePin{awareness.bladeId_.bridgePin_};
        if (
                idMode.choice() == eBIDMode_Bridged and
                bridgePin.val().empty()
           ) {
            return errorMessage(logger, wxTRANSLATE("Pullup Pin cannot be empty."));
        }
    }

    data::String::Context detectPin{awareness.bladeDetect_.pin_};
    data::String::Context idPin{awareness.bladeId_.pin_};
    if (
            data::Bool::Context{awareness.bladeId_.enable_}.val() and
            data::Bool::Context{awareness.bladeDetect_.enable_}.val() and
            detectPin.val() == idPin.val()
       ) {
        return errorMessage(logger, wxTRANSLATE("Blade ID Pin and Blade Detect Pin cannot be the same."));
    }

    data::Vector::Context bladeConfigs{config.bladeConfigs_};
    for (const auto& model : bladeConfigs.children()) {
        auto& bladeConfig{static_cast<BladeConfig&>(*model)};

        data::Integer::Context issues{bladeConfig.issues_};
        if (issues.val() != BladeConfig::eIssue_None) {
            return errorMessage(logger, blades::BladeConfig::issueString(issues.val()));
        }
    }

    for (
            auto arrayIdx{0};
            arrayIdx < bladeConfigs.children().size();
            ++arrayIdx
        ) {
        const auto& model{bladeConfigs.children()[arrayIdx]};
        auto& bladeConfig{static_cast<BladeConfig&>(*model)};

        data::String::Context name{bladeConfig.name_};

        data::Choice::Context selectedPresetsArray{
            bladeConfig.presetArray_.choice_
        };

        if (selectedPresetsArray.choice() == -1) {
            return errorMessage(logger, wxTRANSLATE("Blade array %s has no preset array selection"), name.val());
        }

        data::Vector::Context blades{bladeConfig.blades_};

        for (
                auto bladeIdx{0};
                bladeIdx < blades.children().size();
                ++bladeIdx
            ) {
            const auto& model{blades.children()[bladeIdx]};
            auto& blade{static_cast<Blade&>(*model)};

            data::Choice::Context type{blade.type_.choice_};

            if (type.choice() == Blade::eWS281X) {
                data::String::Context dataPin{blade.ws281x().dataPin_};

                if (dataPin.val().empty()) {
                    return errorMessage(logger, wxTRANSLATE("Blade %d in array %s missing data pin"), bladeIdx, name.val());
                }
                // Subblade overlap
            }

            if (type.choice() == Blade::eSimple) {
                auto& star1{blade.simple().star1_};
                auto& star2{blade.simple().star2_};
                auto& star3{blade.simple().star3_};
                auto& star4{blade.simple().star4_};

                data::Choice::Context star1Led{star1.led_};
                data::Choice::Context star2Led{star2.led_};
                data::Choice::Context star3Led{star3.led_};
                data::Choice::Context star4Led{star4.led_};

                constexpr auto SIMPLE_ERR_MSG{wxTRANSLATE("LED %d of blade %d in array %s missing power pin.")};
                if (
                        star1Led.choice() != eLED_None and 
                        data::String::Context{star1.powerPin_}.val().empty()
                   ) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 1, bladeIdx, name.val());
                }
                if (
                        star2Led.choice() != eLED_None and 
                        data::String::Context{star2.powerPin_}.val().empty()
                   ) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 2, bladeIdx, name.val());
                }
                if (
                        star3Led.choice() != eLED_None and 
                        data::String::Context{star3.powerPin_}.val().empty()
                   ) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 3, bladeIdx, name.val());
                }
                if (
                        star4Led.choice() != eLED_None and 
                        data::String::Context{star4.powerPin_}.val().empty()
                   ) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 4, bladeIdx, name.val());
                }

                if (
                        star1Led.choice() == eLED_None or
                        star1Led.choice() == eLED_None or
                        star1Led.choice() == eLED_None or
                        star1Led.choice() == eLED_None
                   ) {
                    return errorMessage(logger, wxTRANSLATE("Blade %d in array %s has no LEDs"), bladeIdx, name.val());
                }
            }
        }
    }

    data::Vector::Context presetArrays{config.presetArrays_};
    for (const auto& model : presetArrays.children()) {
        auto& presetArray{static_cast<presets::Array&>(*model)};

        data::String::Context arrayName{presetArray.name_};
        if (arrayName.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Preset array has no name"));
        }

        for (const auto& model : presetArrays.children()) {
            auto& checkArray{static_cast<presets::Array&>(*model)};

            if (&checkArray == &presetArray) continue;

            data::String::Context checkName{checkArray.name_};
            if (checkName.val() == arrayName.val()) {
                return errorMessage(logger, wxTRANSLATE("Duplicate preset arrays %s"), arrayName.val());
            }
        }
    }

    constexpr cstring STYLE_ERR_STR{wxTRANSLATE("Bladestyle %d in preset %d (%s) in array %s has mismatched %s")};
    for (const auto& model : presetArrays.children()) {
        auto& presetArray{static_cast<presets::Array&>(*model)};

        data::String::Context arrayName{presetArray.name_};
        data::Vector::Context presets{presetArray.presets_};

        for (
                auto presetIdx{0};
                presetIdx < presets.children().size();
                ++presetIdx
            ) {
            const auto& model{presets.children()[presetIdx]};
            auto& preset{static_cast<presets::Preset&>(*model)};

            data::String::Context presetName{preset.name_};
            data::Vector::Context styles{preset.styles_};

            for (
                    auto styleIdx{0};
                    styleIdx < styles.children().size();
                    ++styleIdx
                ) {
                const auto& model{styles.children()[styleIdx]};
                auto& styleModel{static_cast<presets::Style&>(*model)};

                std::vector<char> depth;

                data::String::Context style{styleModel.content_};
                for (const char chr : style.val()) {
                    if (chr == '<' or chr == '(') {
                        depth.push_back(chr);
                        continue;
                    }
                    if (chr == '>' or chr == ')') {
                        if (depth.empty()) {
                            return errorMessage(
                                logger, STYLE_ERR_STR, styleIdx, presetIdx,
                                presetName.val(), arrayName.val(),
                                std::string{chr}
                            );
                        }

                        if (
                                (chr == '>' and depth.back() != '<') or
                                (chr == ')' and depth.back() != '(')
                           ) {
                            return errorMessage(
                                logger, STYLE_ERR_STR, styleIdx, presetIdx,
                                presetName.val(), arrayName.val(),
                                std::string{depth.back(), chr}
                            );
                        }

                        depth.pop_back();
                        continue;
                    }
                    if (chr == '"') {
                        if (not depth.empty() and depth.back() == '"') depth.pop_back();
                        else depth.push_back(chr);
                    }
                }

                if (not depth.empty()) {
                    return errorMessage(
                        logger, STYLE_ERR_STR, styleIdx, presetIdx,
                        presetName.val(), arrayName.val(),
                        std::string{depth.back()}
                    );
                }
            }
        }
    }

    data::Vector::Context buttons{config.buttons_};
    for (auto idx{0}; idx < buttons.children().size(); ++idx) {
        auto& model{*buttons.children()[idx]};
        auto& button{static_cast<buttons::Button&>(model)};

        data::Choice::Context type{button.type_};
        data::Choice::Context event{button.event_};
        data::String::Context pin{button.pin_};

        if (type.choice() == -1) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have a type set."), idx);
        }
        if (event.choice() == -1) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have its event set."), idx);
        }
        if (pin.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have a pin set."), idx);
        }
    }

    return std::nullopt;
}

void outputTop(std::ostream& outFile, Config& config) {
    outFile << "#ifdef CONFIG_TOP\n";
    outputTopGeneral(outFile, config);
    outputTopProp(outFile, config);
    outFile << "#endif\n\n" << std::flush;
}

template<typename VAL>
void outputOpt(std::ostream& outFile, const std::string& opt) {
    outFile << priv::PC_OPT_STR << opt << '\n';
}

template<typename VAL>
void outputOpt(std::ostream& outFile, const std::string& opt, const VAL& val) {
    outFile << priv::PC_OPT_STR << opt << ' ' << val << '\n';
}

template<typename VAL>
void outputDefine(std::ostream& outFile, const std::string& define) {
    outFile << priv::DEFINE_STR << define << '\n';
}

template<typename VAL>
void outputDefine(
    std::ostream& outFile, const std::string& define, const VAL& val
) {
    outFile << priv::DEFINE_STR << define << ' ' << val << '\n';
}

void outputTopGeneral(std::ostream& outFile, Config& config) {
    using namespace config;
    using namespace config::priv;

    auto& settings{config.settings_};

    if (data::Bool::Context{settings.massStorage_}.val()) {
        outputOpt(outFile, ENABLE_MASS_STORAGE_STR);
    }

    if (data::Bool::Context{settings.webUsb_}.val()) {
        outputOpt(outFile, ENABLE_WEBUSB_STR);
    }

    auto osVersion{static_cast<versions::os::Versioned&>(
        *data::Vector::ROContext{config.osVersions()}.children()[
            data::Choice::Context{config.osVersion_.choice_}.choice()
        ]
    ).version_};

    outputOpt(outFile, OS_VERSION_STR, osVersion);

    auto boardInclude{static_cast<versions::os::BoardInfo&>(
        *data::Vector::ROContext{*config.boards()}.children()[
            data::Choice::Context{config.board().choice_}.choice()
        ]
    ).include_};

    outFile << INCLUDE_STR << boardInclude << '\n';

    uint32 requiredLedsPerStrip{0};
    data::Vector::Context bladeConfigs{config.bladeConfigs_};
    for (const auto& model : bladeConfigs.children()) {
        auto& array{static_cast<blades::BladeConfig&>(*model)};
        data::Vector::Context blades{array.blades_};
        for (const auto& model : blades.children()) {
            auto& blade{static_cast<blades::Blade&>(*model)};

            data::Choice::Context type{blade.type_.choice_};
            if (type.choice() != blades::Blade::eWS281X) continue;

            data::Bool::Context whiteMultiplier{blade.ws281x().hasWhite_};
            data::Integer::Context length{blade.ws281x().length_};

            auto ledsInStrip{length.val()};
            if (whiteMultiplier.val()) {
                ledsInStrip = std::ceil((length.val() * 4.0) / 3.0);
            }

            requiredLedsPerStrip = std::max<uint32>(
                ledsInStrip, requiredLedsPerStrip
            );
        }
    }

    outFile << MAX_LEDS_STR << std::max<uint32>(requiredLedsPerStrip, 144) << ";\n";

    if (utils::Version{8}.compare(osVersion) > 0) {
        // No longer needed in OS8 and newer
        outputDefine(outFile, ENABLE_AUDIO_STR);
        outputDefine(outFile, ENABLE_MOTION_STR);
        outputDefine(outFile, ENABLE_WS2811_STR);
        outputDefine(outFile, ENABLE_SD_STR);
    }

    outputDefine(outFile, SHARED_POWER_PINS_STR);
    outputDefine(outFile, NUM_BLADES_STR, config.numBlades());
    data::Vector::Context buttons{config.buttons_};
    outputDefine(outFile, NUM_BUTTONS_STR, buttons .children().size());

    auto& bladeDetect{settings.bladeAwareness_.bladeDetect_};
    if (data::Bool::Context{bladeDetect.enable_}.val()) {
        data::String::Context pin{bladeDetect.pin_};
        outputDefine(outFile, BLADE_DETECT_PIN_STR, pin.val());
    }

    auto& bladeID{settings.bladeAwareness_.bladeId_};
    if (data::Bool::Context{bladeID.enable_}.val()) {
        data::Choice::Context idMode{bladeID.mode_};
        std::string idString{BLADEID_MODE_STRS[idMode.choice()]};

        idString += data::String::Context{bladeID.pin_}.val();
        if (idMode.choice() == eBIDMode_External) {
            data::Integer::Context pullup{bladeID.pullup_};
            (idString += ", ") += std::to_string(pullup.val());
        } else if (idMode.choice() == eBIDMode_Bridged) {
            data::String::Context bridgePin{bladeID.bridgePin_};
            (idString += ", ") += bridgePin.val();
        }
        idString += ">\n";
        outputDefine(outFile, BLADE_ID_CLASS_STR, idString);
 
        data::Selection::Context powerPins{bladeID.powerPins_};
        if (
                data::Bool::Context{bladeID.powerForId_}.val() and
                std::ranges::any_of(powerPins.selected(), std::identity{})
           ) {
            std::string powerString{POWER_PINS_STR};

            for (auto idx{0}; idx < powerPins.items().size(); ++idx) {
                if (not powerPins.selected()[idx]) continue;

                powerString += powerPins.items()[idx];
                if (idx + 1 < powerPins.items().size()) powerString += ", ";
            }

            powerString += ">\n";
            outputDefine(outFile, ENABLE_POWER_FOR_ID_STR, powerString);
        }

        if (data::Bool::Context{bladeID.continuousScanning_}.val()) {
            data::Integer::Context itvl{bladeID.continuousInterval_};
            data::Integer::Context times{bladeID.continuousTimes_};
            outputDefine(outFile, BLADE_ID_SCAN_MILLIS_STR, itvl.val());
            outputDefine(outFile, BLADE_ID_TIMES_STR, times.val());
        }
    }

    data::Integer::Context volume{settings.volume_};
    outputDefine(outFile, VOLUME_STR, volume.val());
    if (data::Bool::Context{settings.enableBootVolume_}.val()) {
        data::Integer::Context bootVolume{settings.bootVolume_};
        outputDefine(outFile, BOOT_VOLUME_STR, bootVolume.val());
    }

    data::Decimal::Context clashThresh{settings.clashThreshold_};
    outputDefine(outFile, CLASH_THRESHOLD_STR, clashThresh.val());

    data::Decimal::Context pliOff{settings.pliOffTime_};
    auto pliOffCalced{static_cast<uint32>(std::ceil(pliOff.val() * 1000))};
    outputDefine(outFile, PLI_OFF_STR, pliOffCalced);

    data::Decimal::Context idleOff{settings.idleOffTime_};
    auto idleOffCalced{static_cast<uint32>(std::ceil(idleOff.val() * 60))};
    const auto idleOffString{std::to_string(idleOffCalced) + " * 1000"};
    outputDefine(outFile, IDLE_OFF_STR, idleOffString);

    data::Decimal::Context motionOff{settings.motionTimeout_};
    auto motionOffCalced{static_cast<uint32>(std::ceil(motionOff.val() * 60))};
    const auto motionOffString{std::to_string(motionOffCalced) + " * 1000"};
    outputDefine(outFile, MOTION_TIMEOUT_STR, motionOffString);

    if (data::Bool::Context{settings.disableColorChange_}.val()) {
        outputDefine(outFile, DISABLE_COLOR_CHANGE_STR);
    }

    if (data::Bool::Context{settings.disableBasicParserStyles_}.val()) {
        outputDefine(outFile, DISABLE_BASIC_PARSERS_STR);
    }

    if (data::Bool::Context{settings.disableDiagnosticCommands_}.val()) {
        outputDefine(outFile, DISABLE_DIAG_COMMANDS_STR);
    }

    // if (config.settings.enableDeveloperCommands) outputDefine(outFile, ENABLE_DEV_COMMANDS_STR);

    if (data::Bool::Context{settings.saveState_}.val()) {
        outputDefine(outFile, SAVE_STATE_STR);
    }

    if (data::Bool::Context{settings.enableAllEditOptions_}.val()) {
        outputDefine(outFile, ENABLE_ALL_EDIT_OPTIONS_STR);
    }

    data::Bool::Context saveVolume{settings.saveVolume_};
    if (saveVolume.val() and saveVolume.enabled()) {
        outputDefine(outFile, SAVE_VOLUME_STR);
    }

    data::Bool::Context savePreset{settings.savePreset_};
    if (savePreset.val() and savePreset.enabled()) {
        outputDefine(outFile, SAVE_PRESET_STR);
    }

    data::Bool::Context saveColor{settings.saveColorChange_};
    if (saveColor.val() and saveColor.enabled()) {
        outputDefine(outFile, SAVE_COLOR_STR);
    }

    if (data::Bool::Context{settings.enableOled_}.val()) {
        outputDefine(outFile, ENABLE_OLED_STR);
    }

    data::Choice::Context orient{settings.orientation_};
    if (orient.choice() != eOrient_Normal) {
        const auto& orientStr{ORIENTATION_STRS[orient.choice()]};
        outputDefine(outFile, ORIENTATION_STR, orientStr);
    }

    data::Integer::Context orientX{settings.orientationRotation_.x_};
    data::Integer::Context orientY{settings.orientationRotation_.y_};
    data::Integer::Context orientZ{settings.orientationRotation_.z_};
    if (
            orientX.val() != 0 or
            orientY.val() != 0 or
            orientZ.val() != 0
       ) {
        std::string rotationStr;
        rotationStr += std::to_string(orientX.val());
        rotationStr += ", ";
        rotationStr += std::to_string(orientY.val());
        rotationStr += ", ";
        rotationStr += std::to_string(orientZ.val());
        outputDefine(outFile, ORIENTATION_ROTATION_STR, rotationStr);
    }

    // if (config.settings.speakTouchValues) outputDefine(outFile, SPEAK_TOUCH_VALUES_STR);

    data::Bool::Context dynDim{settings.dynamicBladeDimming_};
    if (dynDim.val() and dynDim.enabled()) {
        outputDefine(outFile, DYNAMIC_BLADE_DIMMING_STR);
    }

    data::Bool::Context dynLen{settings.dynamicBladeLength_};
    if (dynLen.val() and dynLen.enabled()) {
        outputDefine(outFile, DYNAMIC_BLADE_LENGTH_STR);
    }

    data::Bool::Context dynClash{settings.dynamicClashThreshold_};
    if (dynClash.val() and dynClash.enabled()) {
        outputDefine(outFile, DYNAMIC_CLASH_THRESHOLD_STR);
    }

    data::Bool::Context saveDim{settings.saveBladeDimming_};
    if (saveDim.val() and saveDim.enabled()) {
        outputDefine(outFile, SAVE_BLADE_DIM_STR);
    }

    data::Bool::Context saveClash{settings.saveClashThreshold_};
    if (saveClash.val() and saveClash.enabled()) {
        outputDefine(outFile, SAVE_CLASH_THRESHOLD_STR);
    }

    if (data::Bool::Context{settings.enableFiltering_}.val()) {
        data::Integer::Context cutoff{settings.filterCutoff_};
        data::Integer::Context order{settings.filterOrder_};
        outputDefine(outFile, FILTER_CUTOFF_STR, cutoff.val());
        outputDefine(outFile, FILTER_ORDER_STR, order.val());
    }

    data::Integer::Context clashSuppress{settings.audioClashSuppressionLevel_};
    if (clashSuppress.val() != 10) {
        outputDefine(outFile, AUDIO_CLASH_SUPPRESSION_STR, clashSuppress.val());
    }

    if (data::Bool::Context{settings.dontUseGyroForClash_}.val()) {
        outputDefine(outFile, DONT_USE_GYRO_FOR_CLASH_STR);
    }

    if (data::Bool::Context{settings.femaleTalkie_}.val()) {
        outputDefine(outFile, FEMALE_TALKIE_STR);
    }

    if (data::Bool::Context{settings.disableTalkie_}.val()) {
        outputDefine(outFile, DISABLE_TALKIE_STR);
    }

    if (utils::Version{8}.compare(osVersion) > 0) {
        // Default on newer version
        if (data::Bool::Context{settings.killOldPlayers_}.val()) {
            outputDefine(outFile, KILL_OLD_PLAYERS_STR);
        }

        if (data::Bool::Context{settings.noRepeatRandom_}.val()) {
            outputDefine(outFile, NO_REPEAT_RANDOM_STR);
        } 
    }

    data::Vector::Context defines{settings.defines_};
    for (const auto& model : defines.children()) {
        auto& define{static_cast<settings::Define&>(*model)};

        data::String::Context name{define.name_};
        if (name.val().empty()) continue;

        data::String::Context value{define.value_};
        if (value.val().empty()) outputDefine(outFile, name.val());
        else outputDefine(outFile, name.val(), value.val());
    }
}

void outputTopProp(std::ostream& outFile, Config& config) {
    data::Choice::Context propSel{config.propSel().choice_};
    if (propSel.choice() == -1) return;

    data::Vector::ROContext props{*config.props()};
    const auto& model{props.children()[propSel.choice()]};
    auto& prop{static_cast<versions::props::Prop&>(*model)};

    const auto onEnum{[&](
        data::Model& model, uint64, const std::string&
    ) -> bool {
        auto output{dynamic_cast<versions::props::detail::SettingBase&>(
            model
        ).generateDefineString()};

        if (not output) return false;

        outFile << priv::DEFINE_STR << *output << '\n';
        return false;
    }};
    prop.enumerate(onEnum);

    outFile << std::flush;
}

void outputProp(std::ostream& outFile, Config& config) {
    data::Choice::Context propSel{config.propSel().choice_};
    if (propSel.choice() == -1) return;

    data::Vector::ROContext props{*config.props()};
    const auto& model{props.children()[propSel.choice()]};
    auto& prop{static_cast<versions::props::Prop&>(*model)};

    if (prop.filename_.empty()) return;

    outFile << "#ifdef CONFIG_PROP\n";
    outFile << "#include \"../props/" << prop.filename_ << "\"\n";
    outFile << "#endif\n" << std::flush;
}

void outputPresets(std::ostream& outFile, Config& config) {
    outFile << "#ifdef CONFIG_PRESETS\n";

    data::Vector::Context injections{config.injections_};
    for (const auto& model : injections.children()) {
        auto& injection{static_cast<Injection&>(*model)};

        outFile << "#include \"" << priv::INJECTION_STR.data() << '/';
        outFile << injection.filename_ << "\"\n";
    }
    if (not injections.children().empty()) outFile << '\n';

    outputPresetStyles(outFile, config);
    outputPresetBlades(outFile, config);

    outFile << "#endif\n\n" << std::flush;
}

void outputPresetStyles(std::ostream& outFile, Config& config) {
    const auto numBlades{config.numBlades()};

    data::Vector::Context presetArrays{config.presetArrays_};
    for (const auto& model : presetArrays.children()) {
        auto& presetArray{static_cast<presets::Array&>(*model)};

        data::String::Context arrayName{presetArray.name_};
        outFile << "Preset " << arrayName.val() << "[] = {\n";

        data::Vector::Context presets{presetArray.presets_};
        for (const auto& model : presets.children()) {
            auto& preset{static_cast<presets::Preset&>(*model)};

            data::String::Context fontDir{preset.fontDir_};
            data::String::Context track{preset.track_};
            outFile << "\t{ \"" << fontDir.val() << "\", \""
                << track.val() << "\",\n";

            data::Vector::Context styles{preset.styles_};
            for (auto idx{0}; idx < numBlades; ++idx) {
                const auto& model{styles.children()[idx]};
                auto& style{static_cast<presets::Style&>(*model)};

                std::string line;

                data::String::Context comment{style.comment_};
                auto commentStr{comment.val()};

                utils::trimSurroundingWhitespace(commentStr);

                if (not commentStr.empty()) {
                    std::istringstream commentStream{commentStr};
                    outFile << "\t\t/*\n";
                    while (not false) {
                        std::getline(commentStream, line);
                        outFile << "\t\t * " << line << '\n';
                        if (commentStream.eof()) break;
                    }
                    outFile << "\t\t */\n";
                }

                data::String::Context content{style.content_};
                auto styleStr{content.val()};

                utils::trimWhitespaceOutsideString(styleStr);

                outFile << "\t\t" << styleStr << ",\n";
            }

            data::String::Context presetName{preset.name_};
            outFile << "\t\t\"" << presetName.val() << "\"\n\t},\n";
        }
        outFile << "};\n";
    }
}

void outputPresetBlades(std::ostream& outFile, Config& config) {
    using namespace priv;

    outFile << "BladeConfig blades[] = {\n";

    data::Vector::Context bladeConfigs{config.bladeConfigs_};
    for (const auto& model : bladeConfigs.children()) {
        auto& bladeConfig{static_cast<blades::BladeConfig&>(*model)};

        if (data::Bool::Context{bladeConfig.noBladeId_}.val()) {
            outFile << "\t{ NO_BLADE,\n";
        } else {
            data::Integer::Context id{bladeConfig.id_};
            outFile << "\t{ " << id.val() << ",\n";
        }

        data::Vector::Context blades{bladeConfig.blades_};
        for (const auto& model : blades.children()) {
            auto& blade{static_cast<blades::Blade&>(*model)};

            data::Choice::Context type{blade.type_.choice_};

            if (type.choice() == blades::Blade::eUnassigned) {
                outFile << "\t\tSimpleBladePtr<NoLED, NoLED, NoLED, NoLED, -1, -1, -1, -1>(),\n";
                continue;
            }

            std::stringstream bladeStr;
            data::Integer::Context brightness{blade.brightness_};
            if (brightness.val() != 100) {
                bladeStr << "DimBlade(" << brightness.val() << ", ";
            }

            if (type.choice() == blades::Blade::eWS281X) {
                auto& ws281x{blade.ws281x()};

                data::Integer::Context length{ws281x.length_};
                data::String::Context dataPin{ws281x.dataPin_};

                bladeStr << "WS281XBladePtr<" << length.val() << ", " << dataPin.val();
                bladeStr << ", Color8::";

                if (data::Bool::Context{ws281x.hasWhite_}.val()) {
                    data::Choice::Context order4{ws281x.colorOrder4_};
                    bool whiteFirst{
                        order4.choice() >= eOrder4_White_First_Start and
                        order4.choice() <= eOrder4_White_First_End
                    };

                    if (whiteFirst) {
                        if (data::Bool::Context{ws281x.useRgbWithWhite_}.val()) {
                            bladeStr << 'W';
                        } else bladeStr << 'w';

                        auto strIdx{order4.choice() - eOrder4_White_First_Start};
                        bladeStr << ORDER_STRS[strIdx];
                    } else {
                        bladeStr << ORDER_STRS[order4.choice()];

                        if (data::Bool::Context{ws281x.useRgbWithWhite_}.val()) {
                            bladeStr << 'W';
                        } else bladeStr << 'w';
                    }
                } else {
                    data::Choice::Context order3{ws281x.colorOrder3_};
                    bladeStr << ORDER_STRS[order3.choice()];
                }

                bladeStr << ", " << POWER_PINS_STR;

                data::Selection::Context powerPins{ws281x.powerPins_};
                for (size idx{0}; idx < powerPins.items().size(); ++idx) {
                    if (not powerPins.selected()[idx]) continue;

                    bladeStr << powerPins.items()[idx];
                    if (idx + 1 < powerPins.items().size()) bladeStr << ", ";
                }

                bladeStr << ">>()";
            } else if (type.choice() == blades::Blade::eSimple) {
                auto& simple{blade.simple()};

                bladeStr << "SimpleBladePtr<";

                auto outputStar{[&bladeStr](blades::Simple::Star& star) {
                    data::Choice::Context led{star.led_};

                    bladeStr << LED_STRS[led.choice()];

                    data::Integer::Context resistance{star.resistance_};
                    if (resistance.enabled()) {
                        bladeStr << '<' << resistance.val() << '>';
                    }

                    bladeStr << ", ";
                }};
                outputStar(simple.star1_);
                outputStar(simple.star2_);
                outputStar(simple.star3_);
                outputStar(simple.star4_);

                auto outputStarPower{[&bladeStr](blades::Simple::Star& star) {
                    data::String::Context powerPin{star.powerPin_};
                    
                    if (powerPin.enabled()) {
                        bladeStr << powerPin.val();
                    } else bladeStr << "-1";
                }};
                outputStarPower(simple.star1_);
                bladeStr << ", ";
                outputStarPower(simple.star2_);
                bladeStr << ", ";
                outputStarPower(simple.star3_);
                bladeStr << ", ";
                outputStarPower(simple.star4_);

                bladeStr << ">()";
            }

            if (brightness.val() != 100) bladeStr << ')';

            data::Vector::Context splits{blade.ws281x().splits_};

            if (
                    type.choice() == blades::Blade::eSimple or 
                    (type.choice() == blades::Blade::eWS281X and
                     splits.children().empty())
               ) {
                outFile << "\t\t" << bladeStr.str() << ",\n";
                continue;
            }

            for (const auto& model : splits.children()) {
                auto& split{static_cast<blades::WS281X::Split&>(*model)};

                const auto splitType{split.type_.selected()};

                if (
                        splitType == blades::WS281X::Split::eStandard or
                        splitType == blades::WS281X::Split::eReverse or
                        splitType == blades::WS281X::Split::eList
                   ) {
                    outFile << "\t\t";

                    data::Integer::Context brightness{split.brightness_};
                    if (brightness.val() != 100) {
                        outFile << "DimBlade(" << brightness.val() << ", ";
                    }

                    if (splitType == blades::WS281X::Split::eStandard) {
                        data::Integer::Context start{split.start_};
                        data::Integer::Context end{split.end_};

                        outFile << "SubBlade(" << start.val() << ", "
                            << end.val() << ", ";
                    } else if (splitType == blades::WS281X::Split::eReverse) {
                        data::Integer::Context start{split.start_};
                        data::Integer::Context end{split.end_};

                        outFile << "SubBladeReverse(" << start.val() << ", "
                            << end.val() << ", ";
                    } else if (splitType == blades::WS281X::Split::eList) {
                        data::String::Context list{split.list_};

                        auto listStr{list.val()};
                        if (listStr.back() == ',') listStr.pop_back();

                        outFile << "SubBladeWithList<" << listStr << ">(";
                    }

                    
                    if (&split == &*splits.children().front()) {
                        outFile << bladeStr.str() << ')';                    
                    } else outFile << "nullptr)";

                    if (brightness.val() != 100) outFile << ')';

                    outFile << ",\n";
                }

                if (
                        splitType == blades::WS281X::Split::eStride or
                        splitType == blades::WS281X::Split::eZig_Zag
                   ) {
                    data::Integer::Context segments{split.segments_};

                    for (auto idx{0}; idx < segments.val(); ++idx) {
                        outFile << "\t\t";

                        data::Integer::Context brightness{split.brightness_};
                        if (brightness.val() != 100) {
                            outFile << "DimBlade(" << brightness.val() << ", ";
                        }

                        data::Integer::Context start{split.start_};
                        data::Integer::Context end{split.end_};

                        if (splitType == blades::WS281X::Split::eStride) {
                            const auto endVal{
                                end.val() - (segments.val() - idx - 1)
                            };

                            outFile << "SubBladeWithStride(";
                            outFile << start.val() + idx << ", ";
                            outFile << endVal << ", ";
                            outFile << segments.val() << ", ";
                        } else if (splitType == blades::WS281X::Split::eZig_Zag) {
                            outFile << "SubBladeZZ(";
                            outFile << start.val() << ", " ;
                            outFile << end.val() << ", ";
                            outFile << segments.val() << ", " << idx << ", ";
                        }

                        if (idx == 0 and &split == &*splits.children().front()) {
                            outFile << bladeStr.str() << ')';                    
                        } else outFile << "nullptr)";

                        if (brightness.val() != 100) outFile << ')';

                        outFile << ",\n";
                    }
                }
            }
        }

        data::Choice::Context arrayChoice{bladeConfig.presetArray_.choice_};
        data::Vector::Context presetArrays{config.presetArrays_};
        const auto& arrayModel{presetArrays.children()[arrayChoice.choice()]};
        auto& presetArray{static_cast<presets::Array&>(*arrayModel)};
        data::String::Context presetArrayName{presetArray.name_};
        
        outFile << "\t\tCONFIGARRAY(" << presetArrayName.val() << ")";

        data::String::Context bladeConfigName{bladeConfig.name_};
        if (not bladeConfigName.val().empty()) {
            outFile << ", \"";
            outFile << bladeConfigName.val();
            outFile << '\"';
        }

        outFile << "\n\t},\n";
    }
    outFile << "};\n" << std::flush;
}

void outputButtons(std::ostream& outFile, Config& config) {
    using namespace priv;

    outFile << "#ifdef CONFIG_BUTTONS\n";

    data::Vector::Context buttons{config.buttons_};

    auto idx{1};
    for (const auto& model : buttons.children()) {
        auto& button{static_cast<buttons::Button&>(*model)};

        data::Choice::Context type{button.type_};
        data::Choice::Context event{button.event_};
        data::String::Context pin{button.pin_};

        outFile << BUTTON_TYPE_STRS[type.choice()] << ' ';
        outFile << "Button" << idx << '{';
        outFile << BUTTON_EVENT_STRS[event.choice()] << ", ";
        outFile << pin.val() << ", ";

        if (type.choice() == eBtn_Type_Touch) {
            data::Integer::Context touch{button.touch_};
            outFile << touch.val() << ", ";
        }

        data::String::Context name{button.name_};
        outFile << '"' << name.val() << '"';
        outFile << "};\n";
        ++idx;
    }

    outFile << "#endif\n" << std::flush;
}

} // namespace

