#include "generate.hpp"
/*
 * ProffieConfig, All-In-One Proffieboard Management Utility
 * Copyright (C) 2023-2026 Ryan Ogurek
 *
 * components/config/priv/generate/generate.cpp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <sstream>

#include <wx/translation.h>

#include "config/blades/bladeconfig.hpp"
#include "config/blades/ws281x.hpp"
#include "config/buttons/button.hpp"
#include "config/config.hpp"
#include "config/misc/injection.hpp"
#include "config/presets/array.hpp"
#include "config/presets/preset.hpp"
#include "config/priv/data.hpp"
#include "config/priv/io.hpp"
#include "config/strings.hpp"
#include "config/settings/define.hpp"
#include "data/context.hpp"
#include "log/branch.hpp"
#include "log/logger.hpp"
#include "utils/files.hpp"
#include "utils/string.hpp"
#include "utils/version.hpp"
#include "versions/os.hpp"
#include "versions/prop.hpp"

using namespace config;

namespace {

std::optional<std::string> runPreChecks(
    const Config&, logging::Branch&
);

void outputTop(std::ostream&, const Config&);
void outputTopGeneral(std::ostream&, const Config&);
void outputTopProp(std::ostream&, const Config&);

void outputProp(std::ostream&, const Config&);

void outputPresets(std::ostream&, const Config&);
void outputPresetStyles(std::ostream&, const Config&);
void outputPresetBlades(std::ostream&, const Config&);

void outputButtons(std::ostream&, const Config&);

template <typename VAL = std::string>
void outputOpt(std::ostream&, const std::string& opt, const VAL& val);
template <typename VAL = std::string>
void outputOpt(std::ostream&, const std::string& opt);
template <typename VAL = std::string>
void outputDefine(std::ostream&, const std::string& define);
template <typename VAL = std::string>
void outputDefine(std::ostream&, const std::string& define, const VAL& val);

} // namespace

std::optional<std::string> priv::generate(
    const fs::path& filePath, const Config& config, logging::Branch *lBranch
) {
    auto& logger{logging::Branch::optCreateLogger("generate()", lBranch)};

    std::lock_guard scopeLock{config};

    auto precheckErr{runPreChecks(config, *logger.binfo("Running prechecks..."))};
    if (precheckErr) return precheckErr;

    auto outFile{files::openOutput(filePath)};
    if (not outFile.is_open()) {
        return errorMessage(logger, wxTRANSLATE("Could not open config file for output."));
    }
    
    outFile << "/*\n";
    outFile << " * This configuration file was generated by ProffieConfig, created by Ryryog25.\n";
    outFile << " * ProffieConfig is an All-In-One utility for managing your Proffieboard.\n";
    outFile << " * https://proffieconfig.kafrenetrading.com/\n";
    outFile << " *\n";
    outFile << " * Version: " << executableVersion << ", Generator Version: " wxSTRINGIZE(BIN_VERSION) "\n";
    outFile << " */\n";

    outFile << '\n';
    outputTop(outFile, config);
    outFile << '\n';
    outputProp(outFile, config);
    outFile << '\n';
    outputPresets(outFile, config);
    outFile << '\n';
    outputButtons(outFile, config);

    outFile.close();

    logger.info("Done");
    return std::nullopt;
}

namespace {

std::optional<std::string> runPreChecks(
    const Config& config, logging::Branch& lBranch
) {
    using namespace config;
    using namespace config::priv;
    using namespace config::blades;

    auto& logger{lBranch.createLogger("runPreChecks()")};

    // Right now, the only way to save is in `.h`, but serializing to pconf
    // would remove this restriction.
    //
    // It's a semi-arbitrary restriction, but there might be data loss and
    // things like this.
    if (config.os() == nullptr) {
        return errorMessage(logger, wxTRANSLATE("Config must have an OS Version selected."));
    }

    const auto& settings{config.settings_};
    const auto& awareness{config.settings_.bladeAwareness_};

    auto bladeDetectEnable{data::context(awareness.bladeDetect_.enable_)};
    auto bladeDetectPin{data::context(awareness.bladeDetect_.pin_)};
    if (bladeDetectEnable.val() and bladeDetectPin.val().empty()) {
        return errorMessage(logger, wxTRANSLATE("Blade Detect Pin cannot be empty."));
    }

    auto bladeIDEnable{data::context(awareness.bladeId_.enable_)};
    auto bladeIDPin{data::context(awareness.bladeId_.pin_)};
    if (bladeIDEnable.val()) {
        if (bladeIDPin.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Blade ID Pin cannot be empty."));
        }

        auto mode{data::context(awareness.bladeId_.mode_)};
        auto bridgePin{data::context(awareness.bladeId_.bridgePin_)};
        if (mode.idx() == eBIDMode_Bridged and bridgePin.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Pullup Pin cannot be empty."));
        }
    }

    if (
            bladeIDEnable.val() and
            bladeDetectEnable.val() and
            bladeDetectPin.val() == bladeIDPin.val()
       ) {
        return errorMessage(logger, wxTRANSLATE("Blade ID Pin and Blade Detect Pin cannot be the same."));
    }

    auto bladeConfigs{data::context(config.bladeConfigs_)};
    for (const auto& model : bladeConfigs.children()) {
        auto& bladeConfig{dynamic_cast<BladeConfig&>(*model)};

        auto issues{data::context(bladeConfig.issues())};
        if (issues.val() != BladeConfig::eIssue_None) {
            auto name{data::context(bladeConfig.name_)};
            const auto arrayName{name.val().empty()
                ? _("[default]")
                : name.val()
            };
            return errorMessage(logger, wxTRANSLATE("Blade array %s has issues, and isn't ready yet."), arrayName);
        }
    }

    for (
            auto arrayIdx{0};
            arrayIdx < bladeConfigs.children().size();
            ++arrayIdx
        ) {
        const auto& model{bladeConfigs.children()[arrayIdx]};
        auto& bladeConfig{dynamic_cast<BladeConfig&>(*model)};

        auto name{data::context(bladeConfig.name_)};
        auto presetArray{data::context(bladeConfig.presetArray_)};

        if (presetArray.choiceIdx() == -1) {
            const auto arrayName{name.val().empty()
                ? _("[default]")
                : name.val()
            };
            return errorMessage(logger, wxTRANSLATE("Blade array %s has no preset array selection"), arrayName);
        }

        auto blades{data::context(bladeConfig.blades_)};

        for (
                auto bladeIdx{0};
                bladeIdx < blades.children().size();
                ++bladeIdx
            ) {
            const auto& model{blades.children()[bladeIdx]};
            auto& blade{dynamic_cast<Blade&>(*model)};

            auto type{data::context(blade.type())};

            if (type.choiceIdx() == Blade::eWS281X) {
                auto dataPin{data::context(blade.ws281x().dataPin_)};

                if (dataPin.val().empty()) {
                    return errorMessage(logger, wxTRANSLATE("Blade %d in array %s missing data pin"), bladeIdx, name.val());
                }
                // Subblade overlap
            }

            if (type.choiceIdx() == Blade::eSimple) {
                auto& led1{blade.simple().led1_};
                auto& led2{blade.simple().led2_};
                auto& led3{blade.simple().led3_};
                auto& led4{blade.simple().led4_};

                auto led1Profile{data::context(led1.profile_)};
                auto led2Profile{data::context(led2.profile_)};
                auto led3Profile{data::context(led3.profile_)};
                auto led4Profile{data::context(led4.profile_)};

                auto led1Pin{data::context(led1.powerPin_)};
                auto led2Pin{data::context(led2.powerPin_)};
                auto led3Pin{data::context(led3.powerPin_)};
                auto led4Pin{data::context(led4.powerPin_)};

                constexpr auto SIMPLE_ERR_MSG{wxTRANSLATE("LED %d of blade %d in array %s missing power pin.")};
                if (led1Profile.idx() != eLED_None and led1Pin.val().empty()) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 1, bladeIdx, name.val());
                }
                if (led2Profile.idx() != eLED_None and led2Pin.val().empty()) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 2, bladeIdx, name.val());
                }
                if (led3Profile.idx() != eLED_None and led3Pin.val().empty()) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 3, bladeIdx, name.val());
                }
                if (led4Profile.idx() != eLED_None and led4Pin.val().empty()) {
                    return errorMessage(logger, SIMPLE_ERR_MSG, 4, bladeIdx, name.val());
                }

                if (
                        led1Profile.idx() == eLED_None or
                        led1Profile.idx() == eLED_None or
                        led1Profile.idx() == eLED_None or
                        led1Profile.idx() == eLED_None
                   ) {
                    return errorMessage(logger, wxTRANSLATE("Blade %d in array %s has no LEDs"), bladeIdx, name.val());
                }
            }
        }
    }

    auto presetArrays{data::context(config.presetArrays_)};

    for (const auto& model : presetArrays.children()) {
        auto& presetArray{dynamic_cast<presets::Array&>(*model)};

        auto arrayName{data::context(presetArray.name_)};
        if (arrayName.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Preset array has no name"));
        }

        for (const auto& model : presetArrays.children()) {
            auto& checkArray{dynamic_cast<presets::Array&>(*model)};

            if (&checkArray == &presetArray) continue;

            auto checkName{data::context(checkArray.name_)};
            if (checkName.val() == arrayName.val()) {
                return errorMessage(logger, wxTRANSLATE("Duplicate preset arrays %s"), arrayName.val());
            }
        }
    }

    constexpr cstring STYLE_ERR_STR{wxTRANSLATE("Bladestyle %d in preset %d (%s) in array %s has mismatched %s")};
    for (const auto& model : presetArrays.children()) {
        auto& presetArray{dynamic_cast<presets::Array&>(*model)};

        auto arrayName{data::context(presetArray.name_)};
        auto presets{data::context(presetArray.presets_)};

        for (
                auto presetIdx{0};
                presetIdx < presets.children().size();
                ++presetIdx
            ) {
            const auto& model{presets.children()[presetIdx]};
            auto& preset{dynamic_cast<presets::Preset&>(*model)};

            auto presetName{data::context(preset.name_)};
            auto styles{data::context(preset.styles_)};

            for (
                    auto styleIdx{0};
                    styleIdx < styles.children().size();
                    ++styleIdx
                ) {
                const auto& model{styles.children()[styleIdx]};
                auto& style{dynamic_cast<presets::Style&>(*model)};

                std::vector<char> depth;

                auto content{data::context(style.content_)};
                for (const char chr : content.val()) {
                    if (chr == '<' or chr == '(') {
                        depth.push_back(chr);
                        continue;
                    }
                    if (chr == '>' or chr == ')') {
                        if (depth.empty()) {
                            return errorMessage(
                                logger, STYLE_ERR_STR, styleIdx, presetIdx,
                                presetName.val(), arrayName.val(),
                                std::string{chr}
                            );
                        }

                        if (
                                (chr == '>' and depth.back() != '<') or
                                (chr == ')' and depth.back() != '(')
                           ) {
                            return errorMessage(
                                logger, STYLE_ERR_STR, styleIdx, presetIdx,
                                presetName.val(), arrayName.val(),
                                std::string{depth.back(), chr}
                            );
                        }

                        depth.pop_back();
                        continue;
                    }
                    if (chr == '"') {
                        if (not depth.empty() and depth.back() == '"') depth.pop_back();
                        else depth.push_back(chr);
                    }
                }

                if (not depth.empty()) {
                    return errorMessage(
                        logger, STYLE_ERR_STR, styleIdx, presetIdx,
                        presetName.val(), arrayName.val(),
                        std::string{depth.back()}
                    );
                }
            }
        }
    }

    auto buttons{data::context(config.buttons_)};
    for (auto idx{0}; idx < buttons.children().size(); ++idx) {
        auto& model{*buttons.children()[idx]};
        auto& button{dynamic_cast<buttons::Button&>(model)};

        auto type{data::context(button.type_)};
        auto event{data::context(button.event_)};
        auto pin{data::context(button.pin_)};

        if (type.idx() == -1) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have a type set."), idx);
        }
        if (event.idx() == -1) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have its event set."), idx);
        }
        if (pin.val().empty()) {
            return errorMessage(logger, wxTRANSLATE("Button %u doesn't have a pin set."), idx);
        }
    }

    return std::nullopt;
}

void outputTop(std::ostream& outFile, const Config& config) {
    outFile << "#ifdef CONFIG_TOP\n";
    outputTopGeneral(outFile, config);
    outputTopProp(outFile, config);
    outFile << "#endif\n";
}

template <typename VAL>
void outputOpt(std::ostream& outFile, const std::string& opt) {
    outFile << priv::PC_OPT_STR << opt << '\n';
}

template <typename VAL>
void outputOpt(std::ostream& outFile, const std::string& opt, const VAL& val) {
    outFile << priv::PC_OPT_STR << opt << ' ' << val << '\n';
}

template <typename VAL>
void outputDefine(std::ostream& outFile, const std::string& define) {
    outFile << priv::DEFINE_STR << define << '\n';
}

template <typename VAL>
void outputDefine(
    std::ostream& outFile, const std::string& define, const VAL& val
) {
    outFile << priv::DEFINE_STR << define << ' ' << val << '\n';
}

void outputTopGeneral(std::ostream& outFile, const Config& config) {
    using namespace config;
    using namespace config::priv;

    const auto& settings{config.settings_};

    if (data::context(settings.massStorage_).val()) {
        outputOpt(outFile, ENABLE_MASS_STORAGE_STR);
    }

    if (data::context(settings.webUsb_).val()) {
        outputOpt(outFile, ENABLE_WEBUSB_STR);
    }

    auto osVersion{config.os()->version_};

    outputOpt(outFile, OS_VERSION_STR, osVersion.string());

    auto boardInclude{config.board()->include_};

    outFile << INCLUDE_STR << boardInclude << '\n';

    uint32 requiredLedsPerStrip{0};
    auto bladeConfigs{data::context(config.bladeConfigs_)};
    for (const auto& model : bladeConfigs.children()) {
        auto& array{dynamic_cast<blades::BladeConfig&>(*model)};
        auto blades{data::context(array.blades_)};

        for (const auto& model : blades.children()) {
            auto& blade{dynamic_cast<blades::Blade&>(*model)};

            auto type{data::context(blade.type())};
            if (type.choiceIdx() != blades::Blade::eWS281X) continue;

            auto hasWhite{data::context(blade.ws281x().hasWhite_)};
            auto length{data::context(blade.ws281x().length_)};

            auto ledsInStrip{length.val()};
            if (hasWhite.val()) {
                ledsInStrip = std::ceil((length.val() * 4.0) / 3.0);
            }

            requiredLedsPerStrip = std::max<uint32>(
                ledsInStrip, requiredLedsPerStrip
            );
        }
    }

    outFile << MAX_LEDS_STR << std::max<uint32>(requiredLedsPerStrip, 144) << ";\n";

    if (utils::Version{8}.compare(osVersion) > 0) {
        // No longer needed in OS8 and newer
        outputDefine(outFile, ENABLE_AUDIO_STR);
        outputDefine(outFile, ENABLE_MOTION_STR);
        outputDefine(outFile, ENABLE_WS2811_STR);
        outputDefine(outFile, ENABLE_SD_STR);
    }

    outputDefine(outFile, SHARED_POWER_PINS_STR);
    auto numBlades{data::context(config.numBlades())};
    outputDefine(outFile, NUM_BLADES_STR, numBlades.val());
    auto buttons{data::context(config.buttons_)};
    outputDefine(outFile, NUM_BUTTONS_STR, buttons.children().size());

    const auto& bladeDetect{settings.bladeAwareness_.bladeDetect_};
    if (data::context(bladeDetect.enable_).val()) {
        auto pin{data::context(bladeDetect.pin_)};
        outputDefine(outFile, BLADE_DETECT_PIN_STR, pin.val());
    }

    const auto& bladeID{settings.bladeAwareness_.bladeId_};
    if (data::context(bladeID.enable_).val()) {
        auto mode{data::context(bladeID.mode_)};
        std::string idString{BLADEID_MODE_STRS[mode.idx()]};

        idString += data::context(bladeID.pin_).val();
        if (mode.idx() == eBIDMode_External) {
            auto pullup{data::context(bladeID.pullup_)};
            (idString += ", ") += std::to_string(pullup.val());
        } else if (mode.idx() == eBIDMode_Bridged) {
            auto bridgePin{data::context(bladeID.bridgePin_)};
            (idString += ", ") += bridgePin.val();
        }
        idString += ">\n";
        outputDefine(outFile, BLADE_ID_CLASS_STR, idString);
 
        auto powerPins{data::context(bladeID.powerPins_)};
        if (
                data::context(bladeID.powerForId_).val() and
                std::ranges::any_of(powerPins.selected(), std::identity{})
           ) {
            std::string powerString{POWER_PINS_STR};

            for (auto idx{0}; idx < powerPins.items().size(); ++idx) {
                if (not powerPins.selected()[idx]) continue;

                powerString += powerPins.items()[idx];
                if (idx + 1 < powerPins.items().size()) powerString += ", ";
            }

            powerString += ">\n";
            outputDefine(outFile, ENABLE_POWER_FOR_ID_STR, powerString);
        }

        if (data::context(bladeID.continuous_.enable_).val()) {
            auto itvl{data::context(bladeID.continuous_.interval_)};
            auto times{data::context(bladeID.continuous_.times_)};
            outputDefine(outFile, BLADE_ID_SCAN_MILLIS_STR, itvl.val());
            outputDefine(outFile, BLADE_ID_TIMES_STR, times.val());
        }
    }

    auto volume{data::context(settings.volume_)};
    outputDefine(outFile, VOLUME_STR, volume.val());
    if (data::context(settings.bootVolume_.enable_).val()) {
        auto bootVolume{data::context(settings.bootVolume_.value_)};
        outputDefine(outFile, BOOT_VOLUME_STR, bootVolume.val());
    }

    auto clashThresh{data::context(settings.clashThreshold_)};
    outputDefine(outFile, CLASH_THRESHOLD_STR, clashThresh.val());

    auto pliOff{data::context(settings.pliOffTime_)};
    auto pliOffCalced{static_cast<uint32>(std::ceil(pliOff.val() * 1000))};
    outputDefine(outFile, PLI_OFF_STR, pliOffCalced);

    auto idleOff{data::context(settings.idleOffTime_)};
    auto idleOffCalced{static_cast<uint32>(std::ceil(idleOff.val() * 60))};
    const auto idleOffString{std::to_string(idleOffCalced) + " * 1000"};
    outputDefine(outFile, IDLE_OFF_STR, idleOffString);

    auto motionOff{data::context(settings.motionTimeout_)};
    auto motionOffCalced{static_cast<uint32>(std::ceil(motionOff.val() * 60))};
    const auto motionOffString{std::to_string(motionOffCalced) + " * 1000"};
    outputDefine(outFile, MOTION_TIMEOUT_STR, motionOffString);

    if (data::context(settings.disableColorChange_).val()) {
        outputDefine(outFile, DISABLE_COLOR_CHANGE_STR);
    }

    if (data::context(settings.disableBasicParserStyles_).val()) {
        outputDefine(outFile, DISABLE_BASIC_PARSERS_STR);
    }

    if (data::context(settings.disableDiagnosticCommands_).val()) {
        outputDefine(outFile, DISABLE_DIAG_COMMANDS_STR);
    }

    // if (config.settings.enableDeveloperCommands) outputDefine(outFile, ENABLE_DEV_COMMANDS_STR);

    if (data::context(settings.saveState_).val()) {
        outputDefine(outFile, SAVE_STATE_STR);
    }

    if (data::context(settings.enableAllEditOptions_).val()) {
        outputDefine(outFile, ENABLE_ALL_EDIT_OPTIONS_STR);
    }

    auto saveVolume{data::context(settings.saveVolume_)};
    if (saveVolume.val() and saveVolume.enabled()) {
        outputDefine(outFile, SAVE_VOLUME_STR);
    }

    auto savePreset{data::context(settings.savePreset_)};
    if (savePreset.val() and savePreset.enabled()) {
        outputDefine(outFile, SAVE_PRESET_STR);
    }

    auto saveColor{data::context(settings.saveColorChange_)};
    if (saveColor.val() and saveColor.enabled()) {
        outputDefine(outFile, SAVE_COLOR_STR);
    }

    if (data::context(settings.enableOled_).val()) {
        outputDefine(outFile, ENABLE_OLED_STR);
    }

    auto orient{data::context(settings.orientation_)};
    if (orient.idx() != eOrient_Normal) {
        const auto& orientStr{ORIENTATION_STRS[orient.idx()]};
        outputDefine(outFile, ORIENTATION_STR, orientStr);
    }

    auto orientX{data::context(settings.orientationRotation_.x_)};
    auto orientY{data::context(settings.orientationRotation_.y_)};
    auto orientZ{data::context(settings.orientationRotation_.z_)};
    if (
            orientX.val() != 0 or
            orientY.val() != 0 or
            orientZ.val() != 0
       ) {
        std::string rotationStr;
        rotationStr += std::to_string(orientX.val());
        rotationStr += ", ";
        rotationStr += std::to_string(orientY.val());
        rotationStr += ", ";
        rotationStr += std::to_string(orientZ.val());
        outputDefine(outFile, ORIENTATION_ROTATION_STR, rotationStr);
    }

    // if (config.settings.speakTouchValues) outputDefine(outFile, SPEAK_TOUCH_VALUES_STR);

    auto dynDim{data::context(settings.dynamicBladeDimming_)};
    if (dynDim.val() and dynDim.enabled()) {
        outputDefine(outFile, DYNAMIC_BLADE_DIMMING_STR);
    }

    auto dynLen{data::context(settings.dynamicBladeLength_)};
    if (dynLen.val() and dynLen.enabled()) {
        outputDefine(outFile, DYNAMIC_BLADE_LENGTH_STR);
    }

    auto dynClash{data::context(settings.dynamicClashThreshold_)};
    if (dynClash.val() and dynClash.enabled()) {
        outputDefine(outFile, DYNAMIC_CLASH_THRESHOLD_STR);
    }

    auto saveDim{data::context(settings.saveBladeDimming_)};
    if (saveDim.val() and saveDim.enabled()) {
        outputDefine(outFile, SAVE_BLADE_DIM_STR);
    }

    auto saveClash{data::context(settings.saveClashThreshold_)};
    if (saveClash.val() and saveClash.enabled()) {
        outputDefine(outFile, SAVE_CLASH_THRESHOLD_STR);
    }

    if (data::context(settings.filter_.enable_).val()) {
        auto cutoff{data::context(settings.filter_.cutoff_)};
        auto order{data::context(settings.filter_.order_)};
        outputDefine(outFile, FILTER_CUTOFF_STR, cutoff.val());
        outputDefine(outFile, FILTER_ORDER_STR, order.val());
    }

    auto clashSuppress{data::context(settings.audioClashSuppressionLevel_)};
    if (clashSuppress.val() != 10) {
        outputDefine(outFile, AUDIO_CLASH_SUPPRESSION_STR, clashSuppress.val());
    }

    if (data::context(settings.dontUseGyroForClash_).val()) {
        outputDefine(outFile, DONT_USE_GYRO_FOR_CLASH_STR);
    }

    if (data::context(settings.femaleTalkie_).val()) {
        outputDefine(outFile, FEMALE_TALKIE_STR);
    }

    if (data::context(settings.disableTalkie_).val()) {
        outputDefine(outFile, DISABLE_TALKIE_STR);
    }

    if (utils::Version{8}.compare(osVersion) > 0) {
        // Default on newer version
        if (data::context(settings.killOldPlayers_).val()) {
            outputDefine(outFile, KILL_OLD_PLAYERS_STR);
        }

        if (data::context(settings.noRepeatRandom_).val()) {
            outputDefine(outFile, NO_REPEAT_RANDOM_STR);
        } 
    }

    auto defines{data::context(settings.defines_)};
    for (const auto& model : defines.children()) {
        auto& define{dynamic_cast<settings::Define&>(*model)};

        auto name{data::context(define.name_)};
        if (name.val().empty()) continue;

        auto value{data::context(define.value_)};
        if (value.val().empty()) outputDefine(outFile, name.val());
        else outputDefine(outFile, name.val(), value.val());
    }
}

void outputTopProp(std::ostream& outFile, const Config& config) {
    auto *prop{config.prop()};

    if (prop == nullptr) return;
    
    for (const auto& setting : prop->settings()) {
        auto output{setting->generateDefineString()};

        if (not output) continue;

        outFile << priv::DEFINE_STR << *output << '\n';
    }
}

void outputProp(std::ostream& outFile, const Config& config) {
    auto *prop{config.prop()};

    if (prop == nullptr) return;
    if (prop->filename_.empty()) return;

    outFile << "#ifdef CONFIG_PROP\n";
    outFile << "#include \"../props/" << prop->filename_ << "\"\n";
    outFile << "#endif\n";
}

void outputPresets(std::ostream& outFile, const Config& config) {
    outFile << "#ifdef CONFIG_PRESETS\n";

    auto injections{data::context(config.injections_)};
    for (const auto& model : injections.children()) {
        auto& injection{dynamic_cast<Injection&>(*model)};

        outFile << "#include \"" << priv::INJECTION_STR.data() << '/';
        outFile << injection.filename_ << "\"\n";
    }
    if (not injections.children().empty()) outFile << '\n';

    outputPresetStyles(outFile, config);
    outputPresetBlades(outFile, config);

    outFile << "#endif\n";
}

void outputPresetStyles(std::ostream& outFile, const Config& config) {
    auto numBlades{data::context(config.numBlades())};

    auto presetArrays{data::context(config.presetArrays_)};
    for (const auto& model : presetArrays.children()) {
        auto& presetArray{dynamic_cast<presets::Array&>(*model)};

        auto arrayName{data::context(presetArray.name_)};
        outFile << "Preset " << arrayName.val() << "[] = {\n";

        auto presets{data::context(presetArray.presets_)};
        for (const auto& model : presets.children()) {
            auto& preset{dynamic_cast<presets::Preset&>(*model)};

            auto fontDir{data::context(preset.fontDir_)};
            auto track{data::context(preset.track_)};
            outFile << "\t{ \"" << fontDir.val() << "\", \""
                << track.val() << "\",\n";

            auto styles{data::context(preset.styles_)};
            for (auto idx{0}; idx < numBlades.val(); ++idx) {
                const auto& model{styles.children()[idx]};
                auto& style{dynamic_cast<presets::Style&>(*model)};

                std::string line;

                auto comment{data::context(style.comment_)};
                auto commentStr{comment.val()};

                utils::trimSurroundingWhitespace(commentStr);

                if (not commentStr.empty()) {
                    std::istringstream commentStream{commentStr};
                    outFile << "\t\t/*\n";
                    while (not false) {
                        std::getline(commentStream, line);
                        outFile << "\t\t * " << line << '\n';
                        if (commentStream.eof()) break;
                    }
                    outFile << "\t\t */\n";
                }

                auto content{data::context(style.content_)};
                auto styleStr{content.val()};

                utils::trimWhitespaceOutsideString(styleStr);

                outFile << "\t\t" << styleStr << ",\n";
            }

            auto presetName{data::context(preset.name_)};
            outFile << "\t\t\"" << presetName.val() << "\"\n\t},\n";
        }
        outFile << "};\n";
    }
}

void outputPresetBlades(std::ostream& outFile, const Config& config) {
    using namespace priv;

    outFile << "BladeConfig blades[] = {\n";

    auto bladeConfigs{data::context(config.bladeConfigs_)};
    for (const auto& model : bladeConfigs.children()) {
        auto& bladeConfig{dynamic_cast<blades::BladeConfig&>(*model)};

        if (data::context(bladeConfig.noBladeId_).val()) {
            outFile << "\t{ NO_BLADE,\n";
        } else {
            auto id{data::context(bladeConfig.id_)};
            outFile << "\t{ " << id.val() << ",\n";
        }

        auto blades{data::context(bladeConfig.blades_)};
        for (const auto& model : blades.children()) {
            auto& blade{dynamic_cast<blades::Blade&>(*model)};

            auto type{data::context(blade.type())};

            if (type.choiceIdx() == blades::Blade::eUnassigned) {
                outFile << "\t\tSimpleBladePtr<NoLED, NoLED, NoLED, NoLED, -1, -1, -1, -1>(),\n";
                continue;
            }

            std::stringstream bladeStr;
            auto brightness{data::context(blade.brightness_)};
            if (brightness.val() != 100) {
                bladeStr << "DimBlade(" << brightness.val() << ", ";
            }

            if (type.choiceIdx() == blades::Blade::eWS281X) {
                auto& ws281x{blade.ws281x()};

                auto length{data::context(ws281x.length_)};
                auto dataPin{data::context(ws281x.dataPin_)};

                bladeStr << "WS281XBladePtr<" << length.val() << ", " << dataPin.val();
                bladeStr << ", Color8::";

                if (data::context(ws281x.hasWhite_).val()) {
                    auto order4{data::context(ws281x.colorOrder4_)};
                    bool whiteFirst{
                        order4.idx() >= eOrder4_White_First_Start and
                        order4.idx() <= eOrder4_White_First_End
                    };

                    if (whiteFirst) {
                        if (data::context(ws281x.useRgbWithWhite_).val()) {
                            bladeStr << 'W';
                        } else bladeStr << 'w';

                        auto strIdx{order4.idx() - eOrder4_White_First_Start};
                        bladeStr << ORDER_STRS[strIdx];
                    } else {
                        bladeStr << ORDER_STRS[order4.idx()];

                        if (data::context(ws281x.useRgbWithWhite_).val()) {
                            bladeStr << 'W';
                        } else bladeStr << 'w';
                    }
                } else {
                    auto order3{data::context(ws281x.colorOrder3_)};
                    bladeStr << ORDER_STRS[order3.idx()];
                }

                bladeStr << ", " << POWER_PINS_STR;

                auto powerPins{data::context(ws281x.powerPins_)};
                for (size idx{0}; idx < powerPins.items().size(); ++idx) {
                    if (not powerPins.selected()[idx]) continue;

                    bladeStr << powerPins.items()[idx];
                    if (idx + 1 < powerPins.items().size()) bladeStr << ", ";
                }

                bladeStr << ">>()";
            } else if (type.choiceIdx() == blades::Blade::eSimple) {
                auto& simple{blade.simple()};

                bladeStr << "SimpleBladePtr<";

                auto outputLEDProfile{[&bladeStr](blades::Simple::LED& led) {
                    auto profile{data::context(led.profile_)};

                    bladeStr << LED_STRS[profile.idx()];

                    auto resistance{data::context(led.resistance_)};
                    if (resistance.enabled()) {
                        bladeStr << '<' << resistance.val() << '>';
                    }

                    bladeStr << ", ";
                }};
                outputLEDProfile(simple.led1_);
                outputLEDProfile(simple.led2_);
                outputLEDProfile(simple.led3_);
                outputLEDProfile(simple.led4_);

                auto outputLEDPower{[&bladeStr](blades::Simple::LED& led) {
                    auto powerPin{data::context(led.powerPin_)};
                    
                    if (powerPin.enabled()) {
                        bladeStr << powerPin.val();
                    } else bladeStr << "-1";
                }};
                outputLEDPower(simple.led1_);
                bladeStr << ", ";
                outputLEDPower(simple.led2_);
                bladeStr << ", ";
                outputLEDPower(simple.led3_);
                bladeStr << ", ";
                outputLEDPower(simple.led4_);

                bladeStr << ">()";
            }

            if (brightness.val() != 100) bladeStr << ')';

            auto splits{data::context(blade.ws281x().splits_)};

            if (
                    type.choiceIdx() == blades::Blade::eSimple or
                    (type.choiceIdx() == blades::Blade::eWS281X and
                     splits.children().empty())
               ) {
                outFile << "\t\t" << bladeStr.str() << ",\n";
                continue;
            }

            for (const auto& model : splits.children()) {
                auto& split{dynamic_cast<blades::WS281X::Split&>(*model)};

                auto type{data::context(split.type_)};

                using enum blades::WS281X::Split::Type;

                if (
                        type.selected() == eStandard or
                        type.selected() == eReverse or
                        type.selected() == eList
                   ) {
                    outFile << "\t\t";

                    auto brightness{data::context(split.brightness_)};
                    if (brightness.val() != 100) {
                        outFile << "DimBlade(" << brightness.val() << ", ";
                    }

                    if (type.selected() == eStandard) {
                        auto start{data::context(split.start_)};
                        auto end{data::context(split.end_)};

                        outFile << "SubBlade(" << start.val() << ", "
                            << end.val() << ", ";
                    } else if (type.selected() == eReverse) {
                        auto start{data::context(split.start_)};
                        auto end{data::context(split.end_)};

                        outFile << "SubBladeReverse(" << start.val() << ", "
                            << end.val() << ", ";
                    } else if (type.selected() == eList) {
                        auto list{data::context(split.list_)};

                        auto listStr{list.val()};
                        if (listStr.back() == ',') listStr.pop_back();

                        outFile << "SubBladeWithList<" << listStr << ">(";
                    }

                    
                    if (&split == &*splits.children().front()) {
                        outFile << bladeStr.str() << ')';                    
                    } else outFile << "nullptr)";

                    if (brightness.val() != 100) outFile << ')';

                    outFile << ",\n";
                }

                if (
                        type.selected() == eStride or
                        type.selected() == eZig_Zag
                   ) {
                    auto segments{data::context(split.segments_)};

                    for (auto idx{0}; idx < segments.val(); ++idx) {
                        outFile << "\t\t";

                        auto brightness{data::context(split.brightness_)};
                        if (brightness.val() != 100) {
                            outFile << "DimBlade(" << brightness.val() << ", ";
                        }

                        auto start{data::context(split.start_)};
                        auto end{data::context(split.end_)};

                        if (type.selected() == eStride) {
                            const auto endVal{
                                end.val() - (segments.val() - idx - 1)
                            };

                            outFile << "SubBladeWithStride(";
                            outFile << start.val() + idx << ", ";
                            outFile << endVal << ", ";
                            outFile << segments.val() << ", ";
                        } else if (type.selected() == eZig_Zag) {
                            outFile << "SubBladeZZ(";
                            outFile << start.val() << ", " ;
                            outFile << end.val() << ", ";
                            outFile << segments.val() << ", " << idx << ", ";
                        }

                        if (idx == 0 and &split == &*splits.children().front()) {
                            outFile << bladeStr.str() << ')';                    
                        } else outFile << "nullptr)";

                        if (brightness.val() != 100) outFile << ')';

                        outFile << ",\n";
                    }
                }
            }
        }

        auto arrayChoice{data::context(bladeConfig.presetArray_.choice())};
        auto presetArrays{data::context(config.presetArrays_)};
        const auto& arrayModel{presetArrays.children()[arrayChoice.idx()]};
        auto& presetArray{dynamic_cast<presets::Array&>(*arrayModel)};
        auto presetArrayName{data::context(presetArray.name_)};
        
        outFile << "\t\tCONFIGARRAY(" << presetArrayName.val() << ")";

        auto bladeConfigName{data::context(bladeConfig.name_)};
        if (not bladeConfigName.val().empty()) {
            outFile << ", \"";
            outFile << bladeConfigName.val();
            outFile << '\"';
        }

        outFile << "\n\t},\n";
    }
    outFile << "};\n";
}

void outputButtons(std::ostream& outFile, const Config& config) {
    using namespace priv;

    outFile << "#ifdef CONFIG_BUTTONS\n";

    auto buttons{data::context(config.buttons_)};

    auto idx{1};
    for (const auto& model : buttons.children()) {
        auto& button{dynamic_cast<buttons::Button&>(*model)};

        auto type{data::context(button.type_)};
        auto event{data::context(button.event_)};
        auto pin{data::context(button.pin_)};

        outFile << BUTTON_TYPE_STRS[type.idx()] << ' ';
        outFile << "Button" << idx << '{';
        outFile << BUTTON_EVENT_STRS[event.idx()] << ", ";
        outFile << pin.val() << ", ";

        if (type.idx() == eBtn_Type_Touch) {
            auto touch{data::context(button.touch_)};
            outFile << touch.val() << ", ";
        }

        auto name{data::context(button.name_)};
        outFile << '"' << name.val() << '"';
        outFile << "};\n";
        ++idx;
    }

    outFile << "#endif\n";
}

} // namespace

